apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.useEmptyDirTemp }}
            - mountPath: /usr/local/openresty/nginx/client_body_temp
              name: temp
              subPath: client_body_temp
            - mountPath: /usr/local/openresty/nginx/proxy_temp
              name: temp
              subPath: proxy_temp
            - mountPath: /usr/local/openresty/nginx/fastcgi_temp
              name: temp
              subPath: fastcgi_temp
            - mountPath: /usr/local/openresty/nginx/uwsgi_temp
              name: temp
              subPath: uwsgi_temp
            - mountPath: /usr/local/openresty/nginx/scgi_temp
              name: temp
              subPath: scgi_temp
            - mountPath: /var/log/nginx
              name: temp
              subPath: log
            - mountPath: /usr/local/openresty/nginx/logs
              name: temp
              subPath: openresty-log
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.useEmptyDirTemp }}
      volumes:
        - emptyDir: {}
          name: temp
      {{- end }}
