{{- if and .Values.app.captcha.enabled (eq .Values.app.captcha.secret.name "") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphql.fullname" . }}-captcha
type: Opaque
data:
  turnstileSecret: {{ .Values.app.captcha.turnstile.secret | b64enc }}
{{- end }}
