{{- if and .Values.app.mailer.enabled .Values.app.mailer.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.app.mailer.secretName }}"
type: Opaque
data:
  user: "{{ .Values.app.mailer.user | b64enc }}"
  password: "{{ .Values.app.mailer.password | b64enc }}"
  sender: "{{ .Values.app.mailer.sender | b64enc }}"
{{- end }}
