apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "graphql.fullname" . }}-database-migration
  labels:
    {{- include "graphql.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  template:
    spec:
      serviceAccountName: {{ include "graphql.serviceAccountName" . }}
      initContainers:
        - name: empty-file
          image: alpine
          command: ["sh", "-c", "touch /mnt/schema.gql"]
          volumeMounts:
          - name: config
            mountPath: /mnt
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        command: ["yarn", "predeploy"]
        env:
          - name: NODE_ENV
            value: "{{ .Values.env }}"
          - name: AFFINE_ENV
            value: "{{ .Values.env }}"
          - name: DEPLOYMENT_TYPE
            value: "{{ .Values.global.deployment.type }}"
          - name: DEPLOYMENT_PLATFORM
            value: "{{ .Values.global.deployment.platform }}"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ default (print (include "graphql.fullname" .) "-pg" ) .Values.global.database.secret.name }}
                key: {{ .Values.global.database.secret.key }}
          - name: DATABASE_URL
            value: postgres://{{ .Values.global.database.user }}:$(DATABASE_PASSWORD)@{{ .Values.global.database.host }}:{{ .Values.global.database.port }}/{{ .Values.global.database.name }}
          - name: REDIS_SERVER_HOST
            value: "{{ .Values.global.redis.host }}"
          - name: REDIS_SERVER_PORT
            value: "{{ .Values.global.redis.port }}"
          - name: REDIS_SERVER_USER
            value: "{{ .Values.global.redis.username }}"
          - name: REDIS_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password
        resources:
          requests:
            cpu: '100m'
            memory: '200Mi'
        volumeMounts:
          - name: config
            mountPath: {{ .Values.app.config.path }}
            subPath: .affine
          - name: config
            mountPath: /app/dist/schema.gql
            subPath: schema.gql
      restartPolicy: Never
      volumes:
        - name: config
          {{- if .Values.app.config.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "graphql.fullname" . }}-config
          {{- else }}
          emptyDir: {}
          {{- end }}
  backoffLimit: 1
