{{- if (not .Values.global.database.secret.name) .Values.global.database.secret.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "graphql.fullname" . }}-pg"
type: Opaque
data:
  {{ .Values.global.database.secret.key }}: {{ .Values.global.database.secret.password | b64enc }}
{{- end }}
