{{- if and (eq .Values.global.redis.secret.name "") .Values.global.redis.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphql.fullname" . }}-redis
type: Opaque
data:
  {{ .Values.global.redis.secret.key }}: {{ .Values.global.redis.secret.password | b64enc }}
{{- end }}
